development:
  adapter: postgresql
  encoding: unicode
  database: basicsoa_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: basicsoa_test
  pool: 5
  username: postgres
